name: Build & Deploy
on: 
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy Ruby on Rails App
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          passphrase: ${{secrets.SSH_PASSPHRASE}}

          script: |
            git clone https://github.com/Korbisch/blog.git /home/rails/test-deployment
            echo 'Deployment successful to Digital Ocean'
